version: '3.8'
services:
  db:
    image: postgres:15
    container_name: autoservis-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: heslo123
      POSTGRES_DB: autoservis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: