# P?ipojení k databázi (URL, u?ivatel, heslo)
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# Hibernate nastavení (ORM)
# 'update' zajistí, ?e Java sama vytvo?í nebo upraví tabulky v databázi podle tvých t?íd
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

# Dialekt pro PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Zobrazení SQL dotaz? v konzoli (pro kontrolu, co Java d?lá)
spring.jpa.show-sql=true